version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bank-account-management
    restart: always
    environment:
      POSTGRES_DB: bankAccountManagement
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    name: bank-account-management-db
